stages:   
  - clone 
  - build

webapp-clone:   
  stage: clone   
  script:     
    - git pull origin dev 
  rules:     
    - if: $CI_COMMIT_BRANCH == 'dev'

webapp-build:
  stage: build
  script:
    - ionic build --prod
  
