stages:   
  - clone 
  - build

webapp-clone:   
  stage: clone   
  script:     
    - cd $DEPLOY_DIR
    - sudo git pull
  rules:     
    - if: $CI_COMMIT_BRANCH == 'dev'

webapp-build:
  stage: build
  script:
    - cd $DEPLOY_DIR
    - sudo ionic build --prod --verbose
  rules:
    - if: $CI_COMMIT_BRANCH == 'dev'
  retry:
    max: 2
    when:
      - script_failure  
  
